apiVersion: field.vmware.com/v1
kind: ArgoCluster
metadata:
  name: cl02
  namespace: workload-ns
spec:
  clusterName: "cl02"
  argoNamespace: "argocd-instance-1"
  clusterLabels:
    env: "lab"
    team: "platform"
  project: default
