apiVersion: v1
kind: Secret
metadata:
  name: demo-cluster-authentication-config
  namespace: test-namespace
type: Opaque
stringData:
  authentication-config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1beta1
    kind: AuthenticationConfiguration
    jwt:
    - issuer:
        url: https://10.13.10.251:8443/realms/vks-realm
        certificateAuthority: |
          -----BEGIN CERTIFICATE-----
          MIIFKzCCAxOgAwIBAgIUH/ylHRH79TM5Q/lw73i61E6E/FwwDQYJKoZIhvcNAQEL
          BQAwFzEVMBMGA1UEAwwMMTAuMTMuMTAuMjUxMB4XDTI2MDUxMTA1NDEyMloXDTI3
          MDUxMTA1NDEyMlowFzEVMBMGA1UEAwwMMTAuMTMuMTAuMjUxMIICIjANBgkqhkiG
          9w0BAQEFAAOCAg8AMIICCgKCAgEAvfT82Wt4JHwOYDrdkXQkB8nPtPvhvXBodSfg
          1XfKKG1/dyqkZxA6ohdmxImMR1FIUg2DMPdPUW6KbFBOwDJSlrnMzrS+GjnagOCi
          d9CZiWVtWlAHOla3sOuCBl0ftOJrh9qqAmszSVPkvIi4+jrG7qLtIv+uooPGQ+V3
          uo+QhQ3cwmsKtYQyY303SuKHOGXxs/wDpdVf9cFUW0JoYRMkHhQPrFjm+4gvHQO8
          +Una+bnN01BrmqJsvXO5UY4X6sll5h2KthyTvApKQ3er+SwAdDRmkGu0QC899mDO
          cB6h6uOHThs7BV4uO4kVy1UVwFehk1pEWkOqLPYcv1wbnwy9Iq+hBjhZa9r0SBDi
          ZmxCmo7BxEgl2dr1Q4Xd1z9P+aGchw8uTOWMsck6G8Q58tuImaqkpYh1thXxtQ2j
          MwQ+bei3+WBcGOJ4LuWs1E71GQ4Ty2b4Cft/z/cfPwpPVFHzYJC44LiOKOe20KSD
          MkpWi88XVaQ8Cp4cHuThbMOvYJESc4+GHxwbnHjiI7qGEqcUHuaWud0JR4dwDOoK
          uHJHWPw6L5FPRsJRMTeRuT9pdT9tawq5ECWnw2CI9WuM2BzAsRqCJGjyckRQke14
          joWgmdskl1EzS+dj2EkaHZw5/KCBxbzMNwRKmcvH2Alkp+x6x+7Q50B2+mhRvjfV
          kvFWxl0CAwEAAaNvMG0wHQYDVR0OBBYEFMypse6/z+5K4rXwNhXyicP2oQWKMB8G
          A1UdIwQYMBaAFMypse6/z+5K4rXwNhXyicP2oQWKMA8GA1UdEwEB/wQFMAMBAf8w
          GgYDVR0RBBMwEYcECg0K+4IJbG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4ICAQAU
          +Vy3/Q9pA2wzxLbnm4OrXAyNj9DdvQn8zXcnUWDFPPzruBgNWMAlL7Dey5LQUAfM
          zG7oVp4zumqKV9dO4/4k1NCbRtZI9lZqLYxWYbd2sxBAMHLeqN0VN85UqaEM2WrO
          tOddEkxZyVrlK+OKhRUO2RbQiy13BUtx3C6ykTL0nRlH+h6ynOjFP3cR6dLpU9Zy
          YwZ1kjPU5dXxRnQL/YPqDU7AFuDy/9BGBNW8DdfBmVXyouz5SCb2Cenn9Bpf9F7k
          hFc00rIHKw+xNqxqbrvyRbadBM2HRV5UbVJv2XTX9p+b/sev8aRZG7kdwq3yKvRS
          72mBgQslKoJurvRTw73MA3F9UTeURqY+JD8ceE21ChkI8tr333sZ9zNdzOBQgvuW
          WnUqckAEcy2U+DUJ0Jq9hm9qhpJ41lf+wLLIbsu11FAaAR7NzuBAenFpWhMWFkjz
          T2XXiOno7Mpm4XL9eEx56cPJhHJSBhUWuNiIp7myFK6C1guFNuaCfvWehr7/4ZcR
          S7shCmYbT7stpOaeYJO7G/0+0yf8hySDXtfU5+seG07q6BlNyQBTqUzl0BGKwwAh
          iwnTLoaOyovajladhp/t1uq9cVNCzzaNxLzmIFRuFHibn74wjrqICA2q/ZE4PMFm
          X8DFUc9GAmGBwQSwFk6R9i/dnCf7jBXmyVJCv91Y2Q==
          -----END CERTIFICATE-----
        audiences:
        - vks-cluster-client
      claimMappings:
        username:
          claim: sub
          prefix: "keycloak:"
        groups:
          claim: groups
          prefix: "keycloak-group:"

