apiVersion: v1
kind: Secret
metadata:
  # Using the helper is standard practice
  name: {{ include "todo-app.fullname" . }}-auth
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  todopassword: {{ .Values.env.todoPassword | b64enc | quote }}
