apiVersion: v1
kind: Secret
metadata:
  name: github-test-cluster-authentication-config
  namespace: test-namespace
type: Opaque
stringData:
  authentication-config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1beta1
    kind: AuthenticationConfiguration
    jwt:
    - issuer:
        url: https://token.actions.githubusercontent.com
        audiences:
        - "github-test-cluster"
      claimMappings:
        username:
          # This maps the unique GitHub subject (repo:org/repo:ref...) as the K8s user
          claim: sub 
          prefix: "github"
        groups:
          # GitHub tokens don't have a native 'groups' claim by default, 
          # but you can map specific claims to K8s groups if needed.
          groups:
          expression: "'github-org:' + claims.repository_owner"
